# Generated by Django 6.0.5 on 2026-06-13 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalPlaceIdentity',
            new_name='EPI',
        ),
        migrations.RenameModel(
            old_name='RestaurantExperience',
            new_name='RExperience',
        ),
        migrations.RenameModel(
            old_name='UserRestaurantProfile',
            new_name='URProfile',
        ),
        migrations.RemoveConstraint(
            model_name='epi',
            name='unique_external_place_identity',
        ),
        migrations.RemoveConstraint(
            model_name='urprofile',
            name='unique_user_restaurant_profile',
        ),
        migrations.RenameField(
            model_name='epi',
            old_name='external_place_id',
            new_name='external_id',
        ),
        migrations.AddConstraint(
            model_name='epi',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('external_id', 'provider'), name='unique_epi'),
        ),
        migrations.AddConstraint(
            model_name='urprofile',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_urprofile'),
        ),
    ]
