# Generated by Django 6.0.5 on 2026-06-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_externalplaceidentity_epi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epi',
            options={'verbose_name': 'External place identity', 'verbose_name_plural': 'External place identities'},
        ),
        migrations.AlterModelOptions(
            name='rexperience',
            options={'verbose_name': 'Restaurant experience', 'verbose_name_plural': 'Restaurant experiences'},
        ),
        migrations.AlterModelOptions(
            name='urprofile',
            options={'verbose_name': 'User restaurant profile', 'verbose_name_plural': 'User restaurant profiles'},
        ),
    ]
